In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("/content/drive/MyDrive/DATASETS/Iris.csv")

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
x = df.iloc[:, 1:5]
y = df['Species']

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size =0.2)

In [13]:
params = {'learning_rate':np.linspace(0.1,1,10),'n_estimators': range(100, 500, 100),'criterion': ['friedman_mse', 'mse', 'mae']}

In [15]:
gs = GridSearchCV(GradientBoostingClassifier(), params, verbose=1, n_jobs=-1)
best_model = gs.fit(x_train, y_train)

Fitting 5 folds for each of 120 candidates, totalling 600 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   13.4s
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:   52.5s
[Parallel(n_jobs=-1)]: Done 446 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-1)]: Done 600 out of 600 | elapsed:  3.1min finished


In [16]:
best_model.best_estimator_

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.8, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=300,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [17]:
model = best_model.best_estimator_.fit(x_train, y_train)
pred = model.predict(x_test)
acc = accuracy_score(y_test, pred)
clfr = classification_report(y_test, pred)
cfm = confusion_matrix(y_test, pred)

In [18]:
print(acc)
print(cfm)
print(clfr)

0.9333333333333333
[[13  0  0]
 [ 0  8  0]
 [ 0  2  7]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.80      1.00      0.89         8
 Iris-virginica       1.00      0.78      0.88         9

       accuracy                           0.93        30
      macro avg       0.93      0.93      0.92        30
   weighted avg       0.95      0.93      0.93        30

